---
version: '3'

services:

  inference:
    image: inference
    container_name: inference
    build:
      context: ./inference/
      dockerfile: Dockerfile
    volumes:
      - ./train/artifacts/results/:/app/artifacts/results/
      - ./train/data/:/app/data/
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: monitoring_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d monitoring_db -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: