apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  namespace: ml_project_reference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
        - name: inference
          image: inference
          #command: [ "sleep" ]
          #args: [ "infinity" ]
          imagePullPolicy: Never # use the locally built image
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: results-volume
              mountPath: /app/artifacts/results/
            - name: data-volume
              mountPath: /app/data/
      volumes:
        - name: results-volume
          hostPath:
            path: /home/train/artifacts/results/
        - name: data-volume
          hostPath:
            path: /home/train/data/
