apiVersion: v1
kind: Service
metadata:
  name: inference
  namespace: ml_project_reference
spec:
  selector:
    app: inference
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer